---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskdef.json"
        LoadBalancerInfo:
          ContainerName: "bluegreen"
          ContainerPort: 5000
